env: "development"


server:
  timeout: 15s
  idle_timeout: 60s
  host: "0.0.0.0"
  port: 8082
  server_mode: "development"

rate_limiter:
  limit: 10
  window: 1m

grpc:
  host: 0.0.0.0
  port: 50052

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "myappdb"

redis:
  addr: "redis:6379"
  password: "super_secret_password_123"
  db: 0

jwt:
  secret: "mysecretkey"
  expiration_minutes: 15

