env: "development"


server:
  timeout: 15s
  idle_timeout: 60s
  host: "0.0.0.0"
  port: 8082
  server_mode: "development"

grpc:
  host: 0.0.0.0
  port: 50052

database:
  host: "postgres"
  port: 5432
  username: "postgres"
  password: "postgres"
  name: "myappdb"
jwt:
  secret: "mysecretkey"
  expiration_minutes: 15

